FROM node:20-alpine

WORKDIR /usr/src/app

# Copia apenas os package.json para instalar dependências
COPY package*.json ./

RUN npm install

# Copia todo o código
COPY . .

EXPOSE 3001
ENV PORT=3001

CMD ["npm", "run", "dev"]
